### ISSUE TITLE
Assertion failure when using recipe on a target in nested conditional fragment

### ISSUE THREAD

**Issue by wroyca** [build2/build2#269]
The following will produce an assertion failure:

```make
if ($cli.configured)
{
      cli.cxx{hello}: cli{hello}
      {
      }
      {{
      }}
}
```

```make
Core was generated by `b'.
Program terminated with signal SIGABRT, Aborted.
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
Downloading 0.00 MB source file /usr/src/debug/glibc-2.36-9.fc37.x86_64/nptl/pthread_kill.c
44            return INTERNAL_SYSCALL_ERROR_P (ret) ? INTERNAL_SYSCALL_ERRNO (ret) : 0;                                                                                                
[Current thread is 1 (Thread 0x7efea76216c0 (LWP 35715))]
(gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007efea7eafec3 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007efea7e5fa76 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007efea7e497fc in __GI_abort () at abort.c:79
#4  0x00007efea7e4971b in __assert_fail_base (fmt=0x7efea7fbe9e0 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x7efea85db159 "!p.empty ()", 
    file=0x7efea85dcf20 "/home/wroy/Documents/build2/build2-toolchain-0.16.0-a.0.20230220095056.58ebd25f0737/build2/libbuild2/cc/compile-rule.cxx", line=1219, 
    function=<optimized out>) at assert.c:92
#5  0x00007efea7e58656 in __GI___assert_fail (assertion=0x7efea85db159 "!p.empty ()", 
    file=0x7efea85dcf20 "/home/wroy/Documents/build2/build2-toolchain-0.16.0-a.0.20230220095056.58ebd25f0737/build2/libbuild2/cc/compile-rule.cxx", line=1219, 
    function=0x7efea85de0d8 "virtual build2::recipe build2::cc::compile_rule::apply(build2::action, build2::target&) const") at assert.c:101
#6  0x00007efea859b6ed in build2::cc::compile_rule::apply(build2::action, build2::target&) const ()
   from /usr/local/lib/build2/libbuild2-cc-0.16.0-a.0.e9da884cc5e8-0.16.0-a.0.e9da884cc5e8.so
#7  0x00007efea8843c7a in build2::simple_rule::apply(build2::action, build2::target&, build2::match_extra&) const () from /usr/local/lib/build2/libbuild2-0.16.0-a.0.e9da884cc5e8.so
#8  0x00007efea887ec10 in build2::apply_impl(build2::action, build2::target&, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::reference_wrapper<build2::rule const> > const&) () from /usr/local/lib/build2/libbuild2-0.16.0-a.0.e9da884cc5e8.so
#9  0x00007efea88843fe in build2::match_impl(build2::target_lock&, bool, bool) () from /usr/local/lib/build2/libbuild2-0.16.0-a.0.e9da884cc5e8.so
#10 0x00007efea88849e3 in build2::match_impl(build2::action, build2::target const&, unsigned long, std::atomic<unsigned long>*, bool)::{lambda(butl::diag_frame const*, build2::target_lock const*, build2::target&, unsigned long, bool)#1}::operator()(butl::diag_frame const*, build2::target_lock const*, build2::target&, unsigned long, bool) const ()
   from /usr/local/lib/build2/libbuild2-0.16.0-a.0.e9da884cc5e8.so
#11 0x00007efea8884b96 in void build2::scheduler::task_thunk<build2::match_impl(build2::action, build2::target const&, unsigned long, std::atomic<unsigned long>*, bool)::{lambda(butl::diag_frame const*, build2::target_lock const*, build2::target&, unsigned long, bool)#1}, butl::diag_frame const*, build2::target_lock const*, std::reference_wrapper<build2::target>, unsigned long&, bool&>(build2::scheduler&, std::unique_lock<std::mutex>&, void*) () from /usr/local/lib/build2/libbuild2-0.16.0-a.0.e9da884cc5e8.so
#12 0x00007efea87f8617 in build2::scheduler::wait_impl(unsigned long, std::atomic<unsigned long> const&, build2::scheduler::work_queue) ()
   from /usr/local/lib/build2/libbuild2-0.16.0-a.0.e9da884cc5e8.so
#13 0x00007efea85c14d5 in build2::cc::link_rule::apply(build2::action, build2::target&, build2::match_extra&) const ()
   from /usr/local/lib/build2/libbuild2-cc-0.16.0-a.0.e9da884cc5e8-0.16.0-a.0.e9da884cc5e8.so
#14 0x00007efea887ec10 in build2::apply_impl(build2::action, build2::target&, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::reference_wrapper<build2::rule const> > const&) () from /usr/local/lib/build2/libbuild2-0.16.0-a.0.e9da884cc5e8.so
#15 0x00007efea88843fe in build2::match_impl(build2::target_lock&, bool, bool) () from /usr/local/lib/build2/libbuild2-0.16.0-a.0.e9da884cc5e8.so
#16 0x00007efea88849e3 in build2::match_impl(build2::action, build2::target const&, unsigned long, std::atomic<unsigned long>*, bool)::{lambda(butl::diag_frame const*, build2::target_lock const*, build2::target&, unsigned long, bool)#1}::operator()(butl::diag_frame const*, build2::target_lock const*, build2::target&, unsigned long, bool) const ()
   from /usr/local/lib/build2/libbuild2-0.16.0-a.0.e9da884cc5e8.so
#17 0x00007efea8884b96 in void build2::scheduler::task_thunk<build2::match_impl(build2::action, build2::target const&, unsigned long, std::atomic<unsigned long>*, bool)::{lambda(butl::diag_frame const*, build2::target_lock const*, build2:--Type <RET> for more, q to quit, c to continue without paging--
signed long&, bool&>(build2::scheduler&, std::unique_lock<std::mutex>&, void*) () from /usr/local/lib/build2/libbuild2-0.16.0-a.0.e9da884cc5e8.so
#18 0x00007efea87f8617 in build2::scheduler::wait_impl(unsigned long, std::atomic<unsigned long> const&, build2::scheduler::work_queue) () from /usr/local/lib/build2/libbuild2-0.16.0-a.0.e9da884cc5e8.so
#19 0x00007efea86e4263 in build2::wait_guard::wait() () from /usr/local/lib/build2/libbuild2-0.16.0-a.0.e9da884cc5e8.so
#20 0x00007efea8885feb in build2::match_prerequisites(build2::action, build2::target&, std::function<build2::prerequisite_target (build2::action, build2::target const&, build2::prerequisite const&, build2::include_type)> const&, build2::scope const*) () from /usr/local/lib/build2/libbuild2-0.16.0-a.0.e9da884cc5e8.so
#21 0x00007efea884416c in build2::alias_rule::apply(build2::action, build2::target&) const () from /usr/local/lib/build2/libbuild2-0.16.0-a.0.e9da884cc5e8.so
#22 0x00007efea8843c7a in build2::simple_rule::apply(build2::action, build2::target&, build2::match_extra&) const () from /usr/local/lib/build2/libbuild2-0.16.0-a.0.e9da884cc5e8.so
#23 0x00007efea887ec10 in build2::apply_impl(build2::action, build2::target&, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::reference_wrapper<build2::rule const> > const&) ()
   from /usr/local/lib/build2/libbuild2-0.16.0-a.0.e9da884cc5e8.so
#24 0x00007efea88843fe in build2::match_impl(build2::target_lock&, bool, bool) () from /usr/local/lib/build2/libbuild2-0.16.0-a.0.e9da884cc5e8.so
#25 0x00007efea88849e3 in build2::match_impl(build2::action, build2::target const&, unsigned long, std::atomic<unsigned long>*, bool)::{lambda(butl::diag_frame const*, build2::target_lock const*, build2::target&, unsigned long, bool)#1}::operator()(butl::diag_frame const*, build2::target_lock const*, build2::target&, unsigned long, bool) const () from /usr/local/lib/build2/libbuild2-0.16.0-a.0.e9da884cc5e8.so
#26 0x00007efea8884b96 in void build2::scheduler::task_thunk<build2::match_impl(build2::action, build2::target const&, unsigned long, std::atomic<unsigned long>*, bool)::{lambda(butl::diag_frame const*, build2::target_lock const*, build2::target&, unsigned long, bool)#1}, butl::diag_frame const*, build2::target_lock const*, std::reference_wrapper<build2::target>, unsigned long&, bool&>(build2::scheduler&, std::unique_lock<std::mutex>&, void*) ()
   from /usr/local/lib/build2/libbuild2-0.16.0-a.0.e9da884cc5e8.so
#27 0x00007efea87f891d in build2::scheduler::helper(void*) () from /usr/local/lib/build2/libbuild2-0.16.0-a.0.e9da884cc5e8.so
#28 0x00007efea7eae12d in start_thread (arg=<optimized out>) at pthread_create.c:442
#29 0x00007efea7f2fbc0 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

* build2: `0.16.0-a.0.e9da884cc5e8`
* libbutl: `0.16.0-a.0.dbce2c5f2421`
* host: `x86_64-redhat-linux-gnu`

I've attached the logs and a sample to this issue for reference. Let me know if there's any additional information I can provide to help diagnose this issue!

[assert.log](https://github.com/build2/build2/files/10863529/assert.log)
[hello.zip](https://github.com/build2/build2/files/10863539/hello.zip)

**Comment by boris-kolpackov** [comment]
This is the same as #223.
