### ISSUE TITLE
SIGSEGV with $install.resolve when "/" is the first character. 

### ISSUE THREAD

**Issue by wroyca** [build2/build2#393]
$install.resolve tries to access an invalid memory location when "/" is the first character. This can accidentally happen for example if $foo is empty in a $foo/bar scenario.

To reproduce:

```Ruby
$install.resolve([dir_path] /)
```

Backtrace:

```gdb
#0  0x00007ffff7e4b6e4 in butl::basic_path<char, butl::any_path_kind<char> > const& build2::cast<butl::basic_path<char, butl::any_path_kind<char> > >(build2::value const&) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
No symbol table info available.
#1  0x00007ffff7e6d111 in build2::install::resolve(build2::scope const&, build2::target const*, butl::basic_path<char, butl::dir_path_kind<char> >, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const*) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
No symbol table info available.
#2  0x00007ffff7e6f6de in build2::install::resolve_dir(build2::scope const&, build2::target const*, butl::basic_path<char, butl::dir_path_kind<char> >, butl::basic_path<char, butl::dir_path_kind<char> >, bool) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
No symbol table info available.
#3  0x00007ffff7e6fe12 in build2::install::resolve_dir(build2::scope const&, butl::basic_path<char, butl::dir_path_kind<char> >, butl::basic_path<char, butl::dir_path_kind<char> >, bool) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
No symbol table info available.
#4  0x00007ffff7e5d22d in build2::install::functions(build2::function_map&)::{lambda(build2::scope const*, butl::basic_path<char, butl::dir_path_kind<char> >, std::optional<butl::basic_path<char, butl::dir_path_kind<char> > >)#1}::operator()(build2::scope const*, butl::basic_path<char, butl::dir_path_kind<char> >, std::optional<butl::basic_path<char, butl::dir_path_kind<char> > >) const [clone .constprop.0] () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
No symbol table info available.
#5  0x00007ffff7e5dc19 in build2::install::functions(build2::function_map&)::{lambda(build2::scope const*, butl::basic_path<char, butl::dir_path_kind<char> >, std::optional<butl::basic_path<char, butl::dir_path_kind<char> > >)#1}::_FUN(build2::scope const*, butl::basic_path<char, butl::dir_path_kind<char> >, std::optional<butl::basic_path<char, butl::dir_path_kind<char> > >) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
No symbol table info available.
#6  0x00007ffff7e5e952 in build2::function_cast_func<butl::basic_path<char, butl::dir_path_kind<char> >, build2::scope const*, butl::basic_path<char, butl::dir_path_kind<char> >, std::optional<butl::basic_path<char, butl::dir_path_kind<char> > > >::thunk(build2::scope const*, butl::vector_view<build2::value>, void const*) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
No symbol table info available.
#7  0x00007ffff7bd688e in build2::function_family::default_thunk(build2::scope const*, butl::vector_view<build2::value>, build2::function_overload const&) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
No symbol table info available.
#8  0x00007ffff7bd7198 in build2::function_map::call(build2::scope const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, butl::vector_view<build2::value>, build2::location const&, bool) const () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
No symbol table info available.
#9  0x00007ffff7bfb8b7 in build2::parser::parse_names(build2::token&, build2::token_type&, butl::small_vector<build2::name, 1ul>&, build2::parser::pattern_mode, bool, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const*, unsigned long, std::optional<butl::project_name> const&, butl::basic_path<char, butl::dir_path_kind<char> > const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const*, bool, bool) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
No symbol table info available.
#10 0x00007ffff7c3f800 in build2::parser::parse_value(build2::token&, build2::token_type&, build2::parser::pattern_mode, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const*, bool) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
No symbol table info available.
#11 0x00007ffff7c03dee in build2::parser::parse_variable_value(build2::token&, build2::token_type&, bool) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
No symbol table info available.
#12 0x00007ffff7c040f8 in build2::parser::parse_variable(build2::token&, build2::token_type&, build2::variable const&, build2::token_type) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
No symbol table info available.
#13 0x00007ffff7c225ff in build2::parser::parse_clause(build2::token&, build2::token_type&, bool) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
No symbol table info available.
#14 0x00007ffff7c28085 in build2::parser::parse_buildfile(build2::lexer&, build2::scope*, build2::scope&, build2::target*, build2::prerequisite*, bool) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
No symbol table info available.
#15 0x00007ffff7c8d399 in build2::source(build2::parser&, build2::scope&, build2::scope&, build2::lexer&) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
No symbol table info available.
#16 0x00007ffff7c8d97d in build2::source(build2::parser&, build2::scope&, build2::scope&, butl::basic_path<char, butl::any_path_kind<char> > const&) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
No symbol table info available.
#17 0x00007ffff7c8dd04 in build2::source_once(build2::parser&, build2::scope&, build2::scope&, butl::basic_path<char, butl::any_path_kind<char> > const&, build2::scope&) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
No symbol table info available.
#18 0x00007ffff7c94222 in build2::source_once(build2::scope&, build2::scope&, butl::basic_path<char, butl::any_path_kind<char> > const&, build2::scope&) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
No symbol table info available.
#19 0x00007ffff7cf8e49 in build2::dir_search(build2::context&, build2::target const*, build2::prerequisite_key const&) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
No symbol table info available.
#20 0x00007ffff7d0715f in build2::search(build2::target const&, build2::prerequisite_key const&) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
No symbol table info available.
#21 0x00007ffff7d07353 in build2::search(build2::target const&, build2::prerequisite const&) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
No symbol table info available.
#22 0x00007ffff7d0d51b in build2::match_prerequisites(build2::action, build2::target&, std::function<build2::prerequisite_target (build2::action, build2::target const&, build2::prerequisite const&, build2::include_type)> const&, build2::scope const*, bool) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
No symbol table info available.
#23 0x00007ffff7cc0032 in build2::alias_rule::apply(build2::action, build2::target&) const () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
No symbol table info available.
#24 0x00007ffff7cbfaaa in build2::simple_rule::apply(build2::action, build2::target&, build2::match_extra&) const () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
No symbol table info available.
#25 0x00007ffff7d03008 in build2::apply_impl(build2::action, build2::target&, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::reference_wrapper<build2::rule const> > const&) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
No symbol table info available.
#26 0x00007ffff7d0b0d0 in build2::match_impl_impl(build2::target_lock&, unsigned long, bool, bool) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
No symbol table info available.
#27 0x00007ffff7d0c585 in void build2::scheduler::task_thunk<build2::match_impl(build2::action, build2::target const&, unsigned long, unsigned long, std::atomic<unsigned long>*, bool)::{lambda(butl::diag_frame const*, build2::target_lock const*, build2::target&, unsigned long, unsigned long)#1}, butl::diag_frame const*, build2::target_lock const*, std::reference_wrapper<build2::target>, unsigned long&, unsigned long&>(build2::scheduler&, std::unique_lock<std::mutex>&, void*) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
No symbol table info available.
#28 0x00007ffff7c5cd94 in build2::scheduler::wait_impl(unsigned long, std::atomic<unsigned long> const&, build2::scheduler::work_queue) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
No symbol table info available.
#29 0x00007ffff7b58eaf in build2::perform_match(butl::small_vector<build2::value, 1ul> const&, build2::action, build2::action_targets&, unsigned short, bool) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
No symbol table info available.
#30 0x000000000040d4e2 in build2::main(int, char**) ()
No symbol table info available.
#31 0x00007ffff703d088 in __libc_start_call_main () from /lib64/libc.so.6
No symbol table info available.
#32 0x00007ffff703d14b in __libc_start_main_impl () from /lib64/libc.so.6
No symbol table info available.
#33 0x00000000004130c5 in _start ()
No symbol table info available.


registers:
rax            0x7fffffff3f70      140737488306032
rbx            0x7fffffff4080      140737488306304
rcx            0x7fffffff3e70      140737488305776
rdx            0x7fffffff3e70      140737488305776
rsi            0x2d2               722
rdi            0x0                 0
rbp            0x7fffffff4280      0x7fffffff4280
rsp            0x7fffffff3ed0      0x7fffffff3ed0
r8             0x12dec57b4090f35d  1359741270667359069
r9             0x4ac4a0            4900000
r10            0x0                 0
r11            0x7ffff7e4b6e0      140737352349408
r12            0x0                 0
r13            0x0                 0
r14            0x4b9560            4953440
r15            0x4b95b0            4953520
rip            0x7ffff7e4b6e4      0x7ffff7e4b6e4 <butl::basic_path<char, butl::any_path_kind<char> > const& build2::cast<butl::basic_path<char, butl::any_path_kind<char> > >(build2::value const&)+4>
eflags         0x10202             [ IF RF ]
cs             0x33                51
ss             0x2b                43
ds             0x0                 0
es             0x0                 0
fs             0x0                 0
gs             0x0                 0
k0             0x40000             262144
k1             0x0                 0
k2             0x7ffff             524287
k3             0x0                 0
k4             0x0                 0
k5             0x0                 0
k6             0x0                 0
k7             0x0                 0
fs_base        0x7ffff7f83780      140737353627520
gs_base        0x0                 0


current instructions:
=> 0x7ffff7e4b6e4 <_ZN6build24castIN4butl10basic_pathIcNS1_13any_path_kindIcEEEEEERKT_RKNS_5valueE+4>:	cmpb   $0x0,0x8(%rdi)
   0x7ffff7e4b6e8 <_ZN6build24castIN4butl10basic_pathIcNS1_13any_path_kindIcEEEEEERKT_RKNS_5valueE+8>:	jne    0x7ffff7e4b750 <_ZN6build24castIN4butl10basic_pathIcNS1_13any_path_kindIcEEEEEERKT_RKNS_5valueE+112>
   0x7ffff7e4b6ea <_ZN6build24castIN4butl10basic_pathIcNS1_13any_path_kindIcEEEEEERKT_RKNS_5valueE+10>:	mov    (%rdi),%rsi
   0x7ffff7e4b6ed <_ZN6build24castIN4butl10basic_pathIcNS1_13any_path_kindIcEEEEEERKT_RKNS_5valueE+13>:	test   %rsi,%rsi
   0x7ffff7e4b6f0 <_ZN6build24castIN4butl10basic_pathIcNS1_13any_path_kindIcEEEEEERKT_RKNS_5valueE+16>:	je     0x7ffff7e4b731 <_ZN6build24castIN4butl10basic_pathIcNS1_13any_path_kindIcEEEEEERKT_RKNS_5valueE+81>
   0x7ffff7e4b6f2 <_ZN6build24castIN4butl10basic_pathIcNS1_13any_path_kindIcEEEEEERKT_RKNS_5valueE+18>:	mov    0x12e1ff(%rip),%rdx        # 0x7ffff7f798f8
   0x7ffff7e4b6f9 <_ZN6build24castIN4butl10basic_pathIcNS1_13any_path_kindIcEEEEEERKT_RKNS_5valueE+25>:	jmp    0x7ffff7e4b709 <_ZN6build24castIN4butl10basic_pathIcNS1_13any_path_kindIcEEEEEERKT_RKNS_5valueE+41>
   0x7ffff7e4b6fb <_ZN6build24castIN4butl10basic_pathIcNS1_13any_path_kindIcEEEEEERKT_RKNS_5valueE+27>:	nopl   0x0(%rax,%rax,1)
   0x7ffff7e4b700 <_ZN6build24castIN4butl10basic_pathIcNS1_13any_path_kindIcEEEEEERKT_RKNS_5valueE+32>:	mov    0x10(%rsi),%rsi
   0x7ffff7e4b704 <_ZN6build24castIN4butl10basic_pathIcNS1_13any_path_kindIcEEEEEERKT_RKNS_5valueE+36>:	test   %rsi,%rsi
   0x7ffff7e4b707 <_ZN6build24castIN4butl10basic_pathIcNS1_13any_path_kindIcEEEEEERKT_RKNS_5valueE+39>:	je     0x7ffff7e4b731 <_ZN6build24castIN4butl10basic_pathIcNS1_13any_path_kindIcEEEEEERKT_RKNS_5valueE+81>
   0x7ffff7e4b709 <_ZN6build24castIN4butl10basic_pathIcNS1_13any_path_kindIcEEEEEERKT_RKNS_5valueE+41>:	cmp    %rdx,%rsi
   0x7ffff7e4b70c <_ZN6build24castIN4butl10basic_pathIcNS1_13any_path_kindIcEEEEEERKT_RKNS_5valueE+44>:	jne    0x7ffff7e4b700 <_ZN6build24castIN4butl10basic_pathIcNS1_13any_path_kindIcEEEEEERKT_RKNS_5valueE+32>
   0x7ffff7e4b70e <_ZN6build24castIN4butl10basic_pathIcNS1_13any_path_kindIcEEEEEERKT_RKNS_5valueE+46>:	mov    (%rdi),%rax
   0x7ffff7e4b711 <_ZN6build24castIN4butl10basic_pathIcNS1_13any_path_kindIcEEEEEERKT_RKNS_5valueE+49>:	cmpq   $0x0,0x60(%rax)
   0x7ffff7e4b716 <_ZN6build24castIN4butl10basic_pathIcNS1_13any_path_kindIcEEEEEERKT_RKNS_5valueE+54>:	je     0x7ffff7e4b728 <_ZN6build24castIN4butl10basic_pathIcNS1_13any_path_kindIcEEEEEERKT_RKNS_5valueE+72>


threads backtrace:

Thread 3 (Thread 0x7ffff66006c0 (LWP 11625) "b"):
#0  0x00007ffff70a5919 in __futex_abstimed_wait_common () from /lib64/libc.so.6
#1  0x00007ffff70a82e9 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libc.so.6
#2  0x00007ffff72dd700 in std::condition_variable::wait(std::unique_lock<std::mutex>&) () from /lib64/libstdc++.so.6
#3  0x00007ffff7c5de09 in build2::scheduler::helper(void*) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
#4  0x00007ffff70a91b7 in start_thread () from /lib64/libc.so.6
#5  0x00007ffff712b3cc in clone3 () from /lib64/libc.so.6

Thread 2 (Thread 0x7ffff70006c0 (LWP 11611) "b"):
#0  0x00007ffff70a5919 in __futex_abstimed_wait_common () from /lib64/libc.so.6
#1  0x00007ffff70a82e9 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libc.so.6
#2  0x00007ffff72dd700 in std::condition_variable::wait(std::unique_lock<std::mutex>&) () from /lib64/libstdc++.so.6
#3  0x00007ffff7c5d6ff in build2::scheduler::deadlock_monitor(void*) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
#4  0x00007ffff72e7564 in execute_native_thread_routine () from /lib64/libstdc++.so.6
#5  0x00007ffff70a91b7 in start_thread () from /lib64/libc.so.6
#6  0x00007ffff712b3cc in clone3 () from /lib64/libc.so.6

Thread 1 (Thread 0x7ffff7f83780 (LWP 11605) "b"):
#0  0x00007ffff7e4b6e4 in butl::basic_path<char, butl::any_path_kind<char> > const& build2::cast<butl::basic_path<char, butl::any_path_kind<char> > >(build2::value const&) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
#1  0x00007ffff7e6d111 in build2::install::resolve(build2::scope const&, build2::target const*, butl::basic_path<char, butl::dir_path_kind<char> >, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const*) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
#2  0x00007ffff7e6f6de in build2::install::resolve_dir(build2::scope const&, build2::target const*, butl::basic_path<char, butl::dir_path_kind<char> >, butl::basic_path<char, butl::dir_path_kind<char> >, bool) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
#3  0x00007ffff7e6fe12 in build2::install::resolve_dir(build2::scope const&, butl::basic_path<char, butl::dir_path_kind<char> >, butl::basic_path<char, butl::dir_path_kind<char> >, bool) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
#4  0x00007ffff7e5d22d in build2::install::functions(build2::function_map&)::{lambda(build2::scope const*, butl::basic_path<char, butl::dir_path_kind<char> >, std::optional<butl::basic_path<char, butl::dir_path_kind<char> > >)#1}::operator()(build2::scope const*, butl::basic_path<char, butl::dir_path_kind<char> >, std::optional<butl::basic_path<char, butl::dir_path_kind<char> > >) const [clone .constprop.0] () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
#5  0x00007ffff7e5dc19 in build2::install::functions(build2::function_map&)::{lambda(build2::scope const*, butl::basic_path<char, butl::dir_path_kind<char> >, std::optional<butl::basic_path<char, butl::dir_path_kind<char> > >)#1}::_FUN(build2::scope const*, butl::basic_path<char, butl::dir_path_kind<char> >, std::optional<butl::basic_path<char, butl::dir_path_kind<char> > >) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
#6  0x00007ffff7e5e952 in build2::function_cast_func<butl::basic_path<char, butl::dir_path_kind<char> >, build2::scope const*, butl::basic_path<char, butl::dir_path_kind<char> >, std::optional<butl::basic_path<char, butl::dir_path_kind<char> > > >::thunk(build2::scope const*, butl::vector_view<build2::value>, void const*) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
#7  0x00007ffff7bd688e in build2::function_family::default_thunk(build2::scope const*, butl::vector_view<build2::value>, build2::function_overload const&) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
#8  0x00007ffff7bd7198 in build2::function_map::call(build2::scope const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, butl::vector_view<build2::value>, build2::location const&, bool) const () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
#9  0x00007ffff7bfb8b7 in build2::parser::parse_names(build2::token&, build2::token_type&, butl::small_vector<build2::name, 1ul>&, build2::parser::pattern_mode, bool, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const*, unsigned long, std::optional<butl::project_name> const&, butl::basic_path<char, butl::dir_path_kind<char> > const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const*, bool, bool) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
#10 0x00007ffff7c3f800 in build2::parser::parse_value(build2::token&, build2::token_type&, build2::parser::pattern_mode, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const*, bool) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
#11 0x00007ffff7c03dee in build2::parser::parse_variable_value(build2::token&, build2::token_type&, bool) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
#12 0x00007ffff7c040f8 in build2::parser::parse_variable(build2::token&, build2::token_type&, build2::variable const&, build2::token_type) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
#13 0x00007ffff7c225ff in build2::parser::parse_clause(build2::token&, build2::token_type&, bool) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
#14 0x00007ffff7c28085 in build2::parser::parse_buildfile(build2::lexer&, build2::scope*, build2::scope&, build2::target*, build2::prerequisite*, bool) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
#15 0x00007ffff7c8d399 in build2::source(build2::parser&, build2::scope&, build2::scope&, build2::lexer&) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
#16 0x00007ffff7c8d97d in build2::source(build2::parser&, build2::scope&, build2::scope&, butl::basic_path<char, butl::any_path_kind<char> > const&) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
#17 0x00007ffff7c8dd04 in build2::source_once(build2::parser&, build2::scope&, build2::scope&, butl::basic_path<char, butl::any_path_kind<char> > const&, build2::scope&) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
#18 0x00007ffff7c94222 in build2::source_once(build2::scope&, build2::scope&, butl::basic_path<char, butl::any_path_kind<char> > const&, build2::scope&) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
#19 0x00007ffff7cf8e49 in build2::dir_search(build2::context&, build2::target const*, build2::prerequisite_key const&) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
#20 0x00007ffff7d0715f in build2::search(build2::target const&, build2::prerequisite_key const&) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
#21 0x00007ffff7d07353 in build2::search(build2::target const&, build2::prerequisite const&) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
#22 0x00007ffff7d0d51b in build2::match_prerequisites(build2::action, build2::target&, std::function<build2::prerequisite_target (build2::action, build2::target const&, build2::prerequisite const&, build2::include_type)> const&, build2::scope const*, bool) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
#23 0x00007ffff7cc0032 in build2::alias_rule::apply(build2::action, build2::target&) const () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
#24 0x00007ffff7cbfaaa in build2::simple_rule::apply(build2::action, build2::target&, build2::match_extra&) const () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
#25 0x00007ffff7d03008 in build2::apply_impl(build2::action, build2::target&, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::reference_wrapper<build2::rule const> > const&) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
#26 0x00007ffff7d0b0d0 in build2::match_impl_impl(build2::target_lock&, unsigned long, bool, bool) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
#27 0x00007ffff7d0c585 in void build2::scheduler::task_thunk<build2::match_impl(build2::action, build2::target const&, unsigned long, unsigned long, std::atomic<unsigned long>*, bool)::{lambda(butl::diag_frame const*, build2::target_lock const*, build2::target&, unsigned long, unsigned long)#1}, butl::diag_frame const*, build2::target_lock const*, std::reference_wrapper<build2::target>, unsigned long&, unsigned long&>(build2::scheduler&, std::unique_lock<std::mutex>&, void*) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
#28 0x00007ffff7c5cd94 in build2::scheduler::wait_impl(unsigned long, std::atomic<unsigned long> const&, build2::scheduler::work_queue) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
#29 0x00007ffff7b58eaf in build2::perform_match(butl::small_vector<build2::value, 1ul> const&, build2::action, build2::action_targets&, unsigned short, bool) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
#30 0x000000000040d4e2 in build2::main(int, char**) ()
#31 0x00007ffff703d088 in __libc_start_call_main () from /lib64/libc.so.6
#32 0x00007ffff703d14b in __libc_start_main_impl () from /lib64/libc.so.6
#33 0x00000000004130c5 in _start ()
```

**Comment by boris-kolpackov** [comment]
Thanks for the report! Fixed in the latest staged toolchain.
