### ISSUE TITLE
Assertion `*altn == s.root_extra->altn' failed.

### ISSUE THREAD

**Issue by wroyca** [build2/build2#394]
I came across this accidentally. I couldn't replicate it under normal conditions, but I did note what I did when it occurred:

```bash
git clone https://www.github.com/foo/bar.git 
cd bar
bdep init -C @gcc cc
b
cd ..
mv bar baz
bdep new -t empty bar
cd bar
bdep new --package -l c++ -t lib libbar
bdep new --package -l c++ -t exe bar
bdep init -C @gcc cc --wipe
b
cd ../baz
b
```

Backtrace:

```gdb
backtrace:
#0  0x00007ffff70ab144 in __pthread_kill_implementation () from /lib64/libc.so.6
No symbol table info available.
#1  0x00007ffff705365e in raise () from /lib64/libc.so.6
No symbol table info available.
#2  0x00007ffff703b902 in abort () from /lib64/libc.so.6
No symbol table info available.
#3  0x00007ffff703b81e in __assert_fail_base.cold () from /lib64/libc.so.6
No symbol table info available.
#4  0x00007ffff704b977 in __assert_fail () from /lib64/libc.so.6
No symbol table info available.
#5  0x00007ffff7c95a6e in build2::find_project_name(build2::context&, butl::basic_path<char, butl::dir_path_kind<char> > const&, butl::basic_path<char, butl::dir_path_kind<char> > const&, std::optional<bool>, std::optional<bool>&) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
No symbol table info available.
#6  0x00007ffff7c98d67 in build2::find_subprojects(build2::context&, std::map<butl::project_name, butl::basic_path<char, butl::dir_path_kind<char> >, std::less<butl::project_name>, std::allocator<std::pair<butl::project_name const, butl::basic_path<char, butl::dir_path_kind<char> > > > >&, butl::basic_path<char, butl::dir_path_kind<char> > const&, butl::basic_path<char, butl::dir_path_kind<char> > const&, bool) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
No symbol table info available.
#7  0x00007ffff7c9978a in build2::bootstrap_src(build2::scope&, std::optional<bool>&, std::optional<butl::basic_path<char, butl::dir_path_kind<char> > >, bool) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
No symbol table info available.
#8  0x00007ffff7c9b8a9 in build2::create_bootstrap_outer(build2::scope&, bool) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
No symbol table info available.
#9  0x00007ffff7ca23d1 in build2::import_load(build2::context&, std::pair<build2::name, std::optional<butl::basic_path<char, butl::dir_path_kind<char> > > >, bool, build2::location const&) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
No symbol table info available.
#10 0x00007ffff7ca61f6 in build2::import(build2::scope&, build2::name, std::optional<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > const&, bool, bool, build2::location const&) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
No symbol table info available.
#11 0x00007ffff7c2e1fc in build2::parser::parse_import(build2::token&, build2::token_type&) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
No symbol table info available.
#12 0x00007ffff7c22874 in build2::parser::parse_clause(build2::token&, build2::token_type&, bool) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
No symbol table info available.
#13 0x00007ffff7c28085 in build2::parser::parse_buildfile(build2::lexer&, build2::scope*, build2::scope&, build2::target*, build2::prerequisite*, bool) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
No symbol table info available.
#14 0x00007ffff7c8d399 in build2::source(build2::parser&, build2::scope&, build2::scope&, build2::lexer&) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
No symbol table info available.
#15 0x00007ffff7c8d97d in build2::source(build2::parser&, build2::scope&, build2::scope&, butl::basic_path<char, butl::any_path_kind<char> > const&) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
No symbol table info available.
#16 0x00007ffff7c8dd04 in build2::source_once(build2::parser&, build2::scope&, build2::scope&, butl::basic_path<char, butl::any_path_kind<char> > const&, build2::scope&) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
No symbol table info available.
#17 0x00007ffff7c94222 in build2::source_once(build2::scope&, build2::scope&, butl::basic_path<char, butl::any_path_kind<char> > const&, build2::scope&) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
No symbol table info available.
#18 0x000000000040cdfc in build2::main(int, char**) ()
No symbol table info available.
#19 0x00007ffff703d088 in __libc_start_call_main () from /lib64/libc.so.6
No symbol table info available.
#20 0x00007ffff703d14b in __libc_start_main_impl () from /lib64/libc.so.6
No symbol table info available.
#21 0x00000000004130c5 in _start ()
No symbol table info available.


registers:
rax            0x0                 0
rbx            0x3935              14645
rcx            0x7ffff70ab144      140737338061124
rdx            0x6                 6
rsi            0x3935              14645
rdi            0x3935              14645
rbp            0x7ffffffeda80      0x7ffffffeda80
rsp            0x7ffffffeda40      0x7ffffffeda40
r8             0x428010            4358160
r9             0x7                 7
r10            0x8                 8
r11            0x246               582
r12            0x7ffff7f83780      140737353627520
r13            0x7ffff7ed33b0      140737352905648
r14            0x6                 6
r15            0x7ffff7ec5683      140737352849027
rip            0x7ffff70ab144      0x7ffff70ab144 <__pthread_kill_implementation+276>
eflags         0x246               [ PF ZF IF ]
cs             0x33                51
ss             0x2b                43
ds             0x0                 0
es             0x0                 0
fs             0x0                 0
gs             0x0                 0
k0             0xffc00000          4290772992
k1             0xfdffffff          4261412863
k2             0xfff8fcff          4294507775
k3             0x0                 0
k4             0xfffffefe          4294967038
k5             0x0                 0
k6             0x0                 0
k7             0x0                 0
fs_base        0x7ffff7f83780      140737353627520
gs_base        0x0                 0


current instructions:
=> 0x7ffff70ab144 <__pthread_kill_implementation+276>:	mov    %eax,%ebx
   0x7ffff70ab146 <__pthread_kill_implementation+278>:	neg    %ebx
   0x7ffff70ab148 <__pthread_kill_implementation+280>:	cmp    $0xfffff000,%eax
   0x7ffff70ab14d <__pthread_kill_implementation+285>:	mov    $0x0,%eax
   0x7ffff70ab152 <__pthread_kill_implementation+290>:	cmova  %ebx,%eax
   0x7ffff70ab155 <__pthread_kill_implementation+293>:	jmp    0x7ffff70ab0d0 <__pthread_kill_implementation+160>
   0x7ffff70ab15a <__pthread_kill_implementation+298>:	nopw   0x0(%rax,%rax,1)
   0x7ffff70ab160 <__pthread_kill_implementation+304>:	mov    %r13,%rdi
   0x7ffff70ab163 <__pthread_kill_implementation+307>:	call   0x7ffff70a5ba0 <__lll_lock_wake_private>
   0x7ffff70ab168 <__pthread_kill_implementation+312>:	jmp    0x7ffff70ab0b7 <__pthread_kill_implementation+135>
   0x7ffff70ab16d <__pthread_kill_implementation+317>:	nopl   (%rax)
   0x7ffff70ab170 <__pthread_kill_implementation+320>:	mov    %r13,%rdi
   0x7ffff70ab173 <__pthread_kill_implementation+323>:	call   0x7ffff70a5ae0 <__lll_lock_wait_private>
   0x7ffff70ab178 <__pthread_kill_implementation+328>:	jmp    0x7ffff70ab09d <__pthread_kill_implementation+109>
   0x7ffff70ab17d <__pthread_kill_implementation+333>:	call   0x7ffff7138790 <__stack_chk_fail>
   0x7ffff70ab182:	data16 cs nopw 0x0(%rax,%rax,1)


threads backtrace:

Thread 2 (Thread 0x7ffff70006c0 (LWP 14651) "b"):
#0  0x00007ffff70a5919 in __futex_abstimed_wait_common () from /lib64/libc.so.6
#1  0x00007ffff70a82e9 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libc.so.6
#2  0x00007ffff72dd700 in std::condition_variable::wait(std::unique_lock<std::mutex>&) () from /lib64/libstdc++.so.6
#3  0x00007ffff7c5d6ff in build2::scheduler::deadlock_monitor(void*) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
#4  0x00007ffff72e7564 in execute_native_thread_routine () from /lib64/libstdc++.so.6
#5  0x00007ffff70a91b7 in start_thread () from /lib64/libc.so.6
#6  0x00007ffff712b3cc in clone3 () from /lib64/libc.so.6

Thread 1 (Thread 0x7ffff7f83780 (LWP 14645) "b"):
#0  0x00007ffff70ab144 in __pthread_kill_implementation () from /lib64/libc.so.6
#1  0x00007ffff705365e in raise () from /lib64/libc.so.6
#2  0x00007ffff703b902 in abort () from /lib64/libc.so.6
#3  0x00007ffff703b81e in __assert_fail_base.cold () from /lib64/libc.so.6
#4  0x00007ffff704b977 in __assert_fail () from /lib64/libc.so.6
#5  0x00007ffff7c95a6e in build2::find_project_name(build2::context&, butl::basic_path<char, butl::dir_path_kind<char> > const&, butl::basic_path<char, butl::dir_path_kind<char> > const&, std::optional<bool>, std::optional<bool>&) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
#6  0x00007ffff7c98d67 in build2::find_subprojects(build2::context&, std::map<butl::project_name, butl::basic_path<char, butl::dir_path_kind<char> >, std::less<butl::project_name>, std::allocator<std::pair<butl::project_name const, butl::basic_path<char, butl::dir_path_kind<char> > > > >&, butl::basic_path<char, butl::dir_path_kind<char> > const&, butl::basic_path<char, butl::dir_path_kind<char> > const&, bool) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
#7  0x00007ffff7c9978a in build2::bootstrap_src(build2::scope&, std::optional<bool>&, std::optional<butl::basic_path<char, butl::dir_path_kind<char> > >, bool) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
#8  0x00007ffff7c9b8a9 in build2::create_bootstrap_outer(build2::scope&, bool) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
#9  0x00007ffff7ca23d1 in build2::import_load(build2::context&, std::pair<build2::name, std::optional<butl::basic_path<char, butl::dir_path_kind<char> > > >, bool, build2::location const&) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
#10 0x00007ffff7ca61f6 in build2::import(build2::scope&, build2::name, std::optional<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > const&, bool, bool, build2::location const&) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
#11 0x00007ffff7c2e1fc in build2::parser::parse_import(build2::token&, build2::token_type&) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
#12 0x00007ffff7c22874 in build2::parser::parse_clause(build2::token&, build2::token_type&, bool) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
#13 0x00007ffff7c28085 in build2::parser::parse_buildfile(build2::lexer&, build2::sco
pe*, build2::scope&, build2::target*, build2::prerequisite*, bool) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
#14 0x00007ffff7c8d399 in build2::source(build2::parser&, build2::scope&, build2::scope&, build2::lexer&) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
#15 0x00007ffff7c8d97d in build2::source(build2::parser&, build2::scope&, build2::scope&, butl::basic_path<char, butl::any_path_kind<char> > const&) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
#16 0x00007ffff7c8dd04 in build2::source_once(build2::parser&, build2::scope&, build2::scope&, butl::basic_path<char, butl::any_path_kind<char> > const&, build2::scope&) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
#17 0x00007ffff7c94222 in build2::source_once(build2::scope&, build2::scope&, butl::basic_path<char, butl::any_path_kind<char> > const&, build2::scope&) () from /usr/lib/libbuild2-0.17.0-a.0.1455bfe7be36.so
#18 0x000000000040cdfc in build2::main(int, char**) ()
#19 0x00007ffff703d088 in __libc_start_call_main () from /lib64/libc.so.6
#20 0x00007ffff703d14b in __libc_start_main_impl () from /lib64/libc.so.6
#21 0x00000000004130c5 in _start ()
```

**Comment by karen-arutyunov** [comment]
The following commands reproduce the issue reliably:

```
bdep new bar -t exe,alt-naming
cd bar
bdep init -C @gcc cc
b
cd ..
mv bar baz
bdep new -t empty bar
cd bar
bdep new --package -l c++ -t lib libbar
bdep new --package -l c++ -t exe bar
bdep init -C @gcc cc --wipe
b
cd ../baz
b
b: build2/libbuild2/file.cxx:763: butl::project_name build2::find_project_name(context&, const butl::dir_path&, const butl::dir_path&, std::optional<bool>, std::optional<bool>&): Assertion `*altn == s.root_extra->altn' failed.
Aborted (core dumped)

```

**Comment by karen-arutyunov** [comment]
Yet another simpler reproducer:

```
bdep new bar -t exe,alt-naming
cd bar
bdep init -C @gcc cc
b
cd ..
mv bar baz
bdep new bar -t exe
cd bar
bdep init -C @gcc cc --wipe
b
cd ../baz
b
b: build2/libbuild2/file.cxx:763: butl::project_name build2::find_project_name(context&, const butl::dir_path&, const butl::dir_path&, std::optional<bool>, std::optional<bool>&): Assertion `*altn == s.root_extra->altn' failed.
Aborted (core dumped)

```
